import type { Copy } from "../types";
export const missionChapters: Copy[] = [
  ["Signals that do something", "让信号发挥作用"],
  ["Making decisions", "让电路作出判断"],
  ["Working with several bits", "处理多个位"],
  ["Building arithmetic", "构建算术电路"],
  ["Choosing a calculation", "选择运算"],
  ["Remembering values", "保存数值"],
  ["Memory and sequences", "内存与顺序"],
  ["Assembling a computer", "组装计算机"],
  ["Programming your computer", "为计算机编程"],
  ["Useful applications", "实用程序"],
];
export const coreTitles: Copy[] = [
  ["Connect a switch to an output", "把开关连接到输出"],
  ["One switch, two outputs", "用一个开关控制两个输出"],
  ["Both switches turn the light on", "两个开关同时打开才亮"],
  ["Light on when the switch is off", "开关关闭时亮起"],
  ["Build NOT AND: NAND", "构建与非：先与，再非"],
  ["Make an inverter from NAND", "用与非门构建非门"],
  ["Both switches, using NAND", "用与非门实现两个开关同时判断"],
  ["Either switch turns the light on", "任一开关打开即可亮起"],
  ["Detect different inputs: XOR", "检测不同的输入：异或"],
  ["Detect matching inputs: XNOR", "检测相同的输入：同或"],
  ["Choose between two signals", "在两个信号之间选择"],
  ["Choose between four signals", "在四个信号之间选择"],
  ["Build a binary number", "组合一个二进制数"],
  ["Split and rearrange a byte", "拆分并重排字节"],
  ["Logic across a whole byte", "对整个字节进行逻辑运算"],
  ["Select a whole byte", "选择整个字节"],
  ["Select one of eight outputs", "选择八个输出中的一个"],
  ["Display a hexadecimal digit", "显示十六进制数字"],
  ["Add two bits", "将两个位相加"],
  ["Add the incoming carry", "加上输入进位"],
  ["Add two eight-bit numbers", "将两个八位数相加"],
  ["Add one to a number", "给数值加一"],
  ["Represent a negative number", "表示负数"],
  ["Subtract two numbers", "将两个数相减"],
  ["Compare unsigned numbers", "比较无符号数"],
  ["Compare signed numbers", "比较有符号数"],
  ["Report zero, carry, and overflow", "报告零、进位与溢出"],
  ["Shift bits left and right", "将位左移和右移"],
  ["Shift a signed number", "移动有符号数"],
  ["Build a selectable arithmetic unit", "构建可选择运算的算术单元"],
  ["Remember one bit", "记住一个位"],
  ["Remember a whole byte", "记住一个字节"],
  ["Load, hold, and reset a value", "载入、保持和复位数值"],
  ["Count clock steps", "统计时钟步数"],
  ["Keep a running total", "保存累加结果"],
  ["Count and jump between addresses", "递增地址并跳转"],
  ["Write and retrieve stored values", "写入并取回保存的值"],
  ["Choose a memory bank", "选择存储区"],
  ["Look up a value in ROM", "在 ROM 中查找数值"],
  ["Share a bus safely", "安全共享总线"],
  ["Control a traffic light", "控制交通灯"],
  ["Recognize the sequence 101", "识别序列 101"],
  ["Decode an instruction's fields", "拆解指令字段"],
  ["Fetch and remember an instruction", "取出并保存指令"],
  ["Generate instruction control signals", "产生指令控制信号"],
  ["Move values between registers and RAM", "在寄存器与内存间传值"],
  ["Decide when to jump", "判断何时跳转"],
  ["Build and test your CPU", "组装并测试 CPU"],
  ["Encode your first machine-code program", "编写第一个机器码程序"],
  ["Produce output with assembly", "用汇编程序产生输出"],
  ["Store and reload working data", "保存并重新载入数据"],
  ["Choose a program branch", "选择程序分支"],
  ["Repeat work with a counted loop", "用计数循环重复操作"],
  ["Sum a sequence of numbers", "计算数列之和"],
  ["Connect memory-mapped devices", "连接内存映射外设"],
  ["Echo keyboard input", "显示键盘输入"],
  ["Read decimal numbers from text", "从文本读取十进制数"],
  ["Print numbers as decimal text", "把数值输出为十进制文本"],
  ["Calculate addition and subtraction", "实现加法与减法计算"],
  ["Recover from invalid calculator input", "让计算器从错误输入中恢复"],
];
export const projectTitles: Copy[] = [
  ["Repair a disconnected indicator", "修复断开的指示灯"],
  ["Repair crossed signal paths", "修复接反的信号"],
  ["Three-switch safety interlock", "三个开关的安全联锁"],
  ["Master-enable switch", "总控开关"],
  ["Majority-vote indicator", "多数表决指示器"],
  ["Exactly one active input", "检测恰好一个有效输入"],
  ["Configurable alarm", "可控制的报警器"],
  ["Binary-code lock", "二进制密码锁"],
  ["Generate and check parity", "生成并检查奇偶校验"],
  ["Select the highest-priority request", "选择最高优先级请求"],
  ["Count leading zeroes", "统计前导零"],
  ["Reverse bit order", "反转位顺序"],
  ["Find an absolute value", "计算绝对值"],
  ["Stop addition at the maximum", "达到最大值后停止增加"],
  ["Multiply unsigned numbers", "将无符号数相乘"],
  ["Calculate quotient and remainder", "计算商和余数"],
  ["Select minimum and maximum", "选择最小值和最大值"],
  ["Check whether a value is in range", "检查数值是否在范围内"],
  ["Detect a power of two", "判断是否为二的幂"],
  ["Rotate bits in either direction", "双向循环移位"],
  ["Countdown timer", "倒计时器"],
  ["Moving light sequence", "移动的灯光序列"],
  ["Count presses, not held time", "统计按下次数而非按住时长"],
  ["Receive serial bits as a byte", "把串行位接收为字节"],
  ["First-in, first-out queue", "先进先出队列"],
  ["Last-in, first-out stack", "后进先出栈"],
  ["Remember a lock combination", "记住密码输入顺序"],
  ["Copy a bounded memory block", "复制固定长度的内存块"],
  ["Repair an instruction decoder", "修复指令译码器"],
  ["Repair a missing register write", "修复寄存器未写入的问题"],
  ["Read a cycle counter by address", "通过地址读取周期计数"],
  ["Replace control logic with microcode", "用微码实现控制逻辑"],
  ["Multiply with repeated addition", "用重复加法实现乘法"],
  ["Find the greatest common divisor", "计算最大公约数"],
  ["Generate Fibonacci numbers", "生成斐波那契数"],
  ["Sort a four-number array", "排序四个数"],
  ["Convert lowercase text to uppercase", "把小写文本转为大写"],
  ["Draw a pixel pattern", "绘制像素图案"],
  ["Animate a bouncing pixel", "让像素往返移动"],
  ["Build an interactive running total", "交互式累加器"],
];
export const chapterConcepts: Copy[] = [
  [
    "A bit has two values: 0 is off and 1 is on. A connection carries an output value to an input.",
    "位只有两个值：0 为关，1 为开。连接把输出值传给输入。",
  ],
  [
    "Combine the NAND circuit you built to make new decisions. Different constructions can produce the same outputs.",
    "组合你构建的与非电路，实现新的判断。不同的构造可以产生相同的输出。",
  ],
  [
    "A byte contains eight bits. Bit 0 has value 1; each bit to its left doubles that value.",
    "一个字节包含八个位。第 0 位表示 1，往左每一位的值翻倍。",
  ],
  [
    "Carry connects arithmetic columns. Keep the low result bits and expose any extra carry separately.",
    "进位连接各个算术位。保留结果的低位，并单独输出额外进位。",
  ],
  [
    "The same bits can represent unsigned or signed numbers. A calculation must also report how its result should be interpreted.",
    "相同的位可以表示无符号数或有符号数。运算还需要说明如何理解结果。",
  ],
  [
    "Storage changes on a clock step. Its old output is available while the next stored value is calculated.",
    "存储值在时钟步发生时更新。计算下一次存储值时，仍可读取原来的输出。",
  ],
  [
    "An address selects stored data. State records what happened earlier so the same input can lead to a different next action.",
    "地址选择保存的数据。状态记录之前的情况，使相同输入可以产生不同的下一步动作。",
  ],
  [
    "A computer fetches an instruction, selects its operation, then updates only the intended registers or memory.",
    "计算机取出指令、选择操作，然后只更新目标寄存器或内存。",
  ],
  [
    "Your program runs on the circuit CPU. Use instruction stepping to see each instruction change registers, memory, or output.",
    "程序在电路 CPU 上运行。用指令单步观察每条指令如何改变寄存器、内存或输出。",
  ],
  [
    "Programs communicate through device addresses. Read keyboard bytes and write output that a person can use.",
    "程序通过外设地址通信。读取键盘字节，写出人可以使用的结果。",
  ],
];
